version: "3.1"

services:
  userapp:
    image: pavanraj29/nodejs-webapp
    deploy:
      replicas: 2
    ports: 
      - 3000:3000
    depends_on:
      - userappdb

  userappdb:
    image: userapp-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /etc/mysql:/etc/mysql
      - /var/lib/mysql:/var/lib/mysql
