version: "3.1"

services:
  userapp:
    image: hmdemo/userapp
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    ports: 
      - 3030:3030
    depends_on:
      - userappdb

  userappdb:
    image: hmdemo/userappdb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /etc/mysql:/etc/mysql
      - /var/lib/mysql:/usr/local/mysql/data/
